//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RA.AMANDA.Portal.UIFW.Test {
    
    
    public partial class Folder {
        
        /// <summary>
        /// FolderDetails1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RA.AMANDA.Portal.UIFW.Controls.Test.UCFolderDetails FolderDetails1;
    }
}
